#!/bin/bash
set -e

# To use this script on Ubuntu, you will need to first run the following:
# 
# sudo apt install ghc-7.6.3 ghc-7.8.4 ghc-7.10.3 ghc-8.0.2 ghc-8.2.2 ghc-8.4.4 ghc-8.6.2

declare -a ghcs=("7.6.3" "7.8.4" "7.10.3" "8.0.2" "8.2.2" "8.4.4" "8.6.2")

## now loop through the above array
for g in "${ghcs[@]}"
do
   cabal new-haddock --builddir "dist-$g" -w "/opt/ghc/bin/ghc-$g"
done

